version: '3'

services:
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praxi
    volumes:
      - ./index.js:/praxi/index.js
      - ./bot_system:/praxi/bot_system
      - ./update.json:/praxi/update.json
      #  トークンファイルはGitHubに登録されませんBot管理者に問い合わせて用意してください
      - ./token:/praxi/token
      - ./guilds:/praxi/guilds
    tty: true
    # restart: unless-stopped
    command: node index.js
